# Generated by Django 4.2 on 2025-02-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(max_length=100)),
                ('estat', models.CharField(choices=[('pendent', 'Pendent'), ('en_proces', 'En procés'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendent', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('beguda', 'Beguda'), ('aperitiu', 'Aperitiu'), ('plat', 'Plat principal'), ('postre', 'Postre')], max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallsComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.PositiveIntegerField(default=1)),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalls', to='bar.comanda')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.producte')),
            ],
        ),
    ]
